package com.bingkong.bkbase.model;

public class AllColor {
    public static final String TRANSPARENT_COLOR = "#00000000";

    public static final String[] COLOR_HEX = {

            "#CB9CB5",
            "#A78678",
            "#A393D5",
            "#E5A3B3",
            "#AA0221",
            "#9A027B",
            "#EC827F",
            "#93575F",
            "#52185F",
            "#CB2862",
            "#D07E5B",
            "#3F1667",
            "#760220",
            "#7F023B",
            "#370A37",
            "#A3CDCD",
            "#9AB3DD",
            "#D7D8ED",
            "#A1CAD5",
            "#233884",
            "#A2A3B4",
            "#0F7970",
            "#4F34AE",
            "#393849",
            "#154758",
            "#181B2E",
            "#746853",
            "#35454E",
            "#14131B",
            "#EAD744",
            "#470A27",
            "#B61C9A",
            "#243F56",

            "#1097D4",
            "#7088AA",
            "#E1C753",
            "#9B0214",
            "#87856D",
            "#DCC9D6",
            "#818BA7",
            "#938E9F",
            "#4F0B25",
            "#E0DEEB",
            "#DDD1C9",
            "#AD8F77",
            "#B9AEB7",
            "#96291D",
            "#1B1928",
            "#111015",
            "#8D8594",
            "#B18A98",
            "#7D7B89",
            "#5B2E21",
            "#15141B",
            "#AAA59B",
            "#96A7C2",
            "#E7AFB3",
            "#A6A7BE",
            "#C1B6BA",
            "#C1B6BA",
            "#E5E3EF",
            "#C58886",
            "#EDDEE6",
            "#181D24",
            "#EDE59F",
            "#1B1A2F",
            "#CD3F1D",

            "#E3E3F3",
            "#D4D3E5",
            "#2369AF",
            "#2369AF",
            "#15131A",
            "#9C0420",
            "#73021E",
            "#D298BF",
            "#0F2F7B",
            "#CB5B1C",
            "#ABC45E",
            "#C1975A",
            "#B40556",
            "#E7D125",
            "#313A37",
            "#1F264C",
            "#90B5E0",
            "#F08029",
            "#414353",
            "#543989",
            "#DFFA8F",
            "#A8A8B5",
            "#AF2794",
            "#387D4E",
            "#B49D86",
            "#E7F77C",
            "#CA1B1E",
            "#8C8797",
            "#E95C03",
            "#E15394",
            "#272938",
            "#F1ADB2",
            "#2E5296",
            "#94D1DC",

            "#F2F1AF",
            "#AEC2E6",
            "#8783CA",
            "#676685",
            "#8C2193",
            "#4B422B",
            "#EB5450",
            "#870316",
            "#100F16",
            "#DCDBE8",
            "#D4D4EB",
            "#D4D4EB",
            "#5C5D70",
            "#36302D",
            "#512021",
            "#193786",
            "#52051B",
            "#17182D",
            "#432424",
            "#24181D",
            "#B0746C",
            "#3A3440",
            "#D7CFCC",
            "#1D282A",
            "#A7524A",
            "#23121C",
            "#387659",
            "#353441",
            "#634344",
            "#773242",
            "#D7AD22",
            "#DAACD2",
            "#865132",
            "#7A6B64",

            "#C64D8C",
            "#E7E7F5",
            "#980320",
            "#15141A",
            "#DBDCF2",
            "#E2E1EC",
            "#E3E2F3",
            "#CEBCB6",
            "#286D4B",
            "#44295E",
            "#AC1262",
            "#E1B755",
            "#E4C5E1",
            "#1F3D8C",
            "#3B241F",
            "#AB0934",
            "#E0B936",
            "#8DA6D1",
            "#C1B027",
            "#3D162B",
            "#62AEBC",
            "#710523",
            "#C67A14",
            "#451337",
            "#AB9DD5",
            "#CF9EAE",
            "#B5B3C2",
            "#615F6E",
            "#858598",
            "#E8D497",
            "#433F31",
            "#DA5E1A",
            "#AE1C1B",
            "#B4D5DB",

            "#1C406A",
            "#16141B",
            "#C5A89A",
            "#670422",
            "#2A1739",
            "#BC2075",
            "#153289",
            "#7A7871",
            "#AFA5B6",
            "#E4E2ED",
            "#2C4171",
            "#DAB4D3",
            "#161629",
            "#E6CFDD",
            "#341F66",
            "#2D2825",
            "#E9CC13",
            "#73AAD8",
            "#341D21",
            "#8C6794",
            "#D7D44F",
            "#E6BF48",
            "#9893B5",
            "#AB0822",
            "#387D8D",
            "#36805D",
            "#7E6864",
            "#B0818F",
            "#E1CF94",
            "#CA5121",
            "#E8668B",
            "#E4F685",
            "#EC6A5C",
            "#F09814",

            "#E8DB5C",
            "#BB085D",
            "#75B8AA",
            "#99A8DA",
            "#D6E3E6",
            "#25466C",
            "#9679B9",
            "#AE052A",
            "#111015",
            "#E3E4F3",
            "#E7E7F3",
            "#EDC348",
            "#9A3326",
            "#ABC6EA",
            "#1C246B",
            "#2B5A3D",
            "#94C2BA",
            "#CF5E7B",
            "#DED4C9",
            "#70B062",
            "#4F92CF",
            "#7C2A4A",
            "#2F9DBC",
            "#997FC8",
            "#EDD444",
            "#053CA4",
            "#DD0702",
            "#5F0010",
            "#091C1E",
            "#E9DF92",
            "#C33080",
            "#D96336",
            "#0F77C2",
            "#6B3C22",

            "#515B5A",
            "#3C3A47",
            "#C6B1A3",
            "#CBC9D7",
            "#888796",
            "#E4E3EB",
            "#E7CCDA",
            "#3D1223",
            "#B3B1BE",
            "#C1A48F",
            "#726984",
            "#5960A3",
            "#AA022A",
            "#FFFFFF",
            "#E6E6E6",
            "#CCCCCC",
            "#ABABAB",
            "#8B8B8B",
            "#707070",
            "#545454",
            "#333333",
            "#1A1A1A",
            "#000000",
            "#FF9999",
            "#FFCC99",
            "#FFFF99",
            "#CCFF99",
            "#99FF99",
            "#99FFFF",
            "#99CCFF",
            "#9999FF",
            "#CC99FF",
            "#FF99FF",
            "#FF0000",

            "#FF8000",
            "#FFFF00",
            "#80FF00",
            "#00FF00",
            "#00FFFF",
            "#0080FF",
            "#0000FF",
            "#8000FF",
            "#FF00FF",
            "#800000",
            "#804000",
            "#808000",
            "#408000",
            "#008080",
            "#004080",
            "#004080",
            "#000080",
            "#400080",
            "#800080",
            "#FFFFFF",
            "#E6E6E6",
            "#CCCCCC",
            "#ABABAB",
            "#8B8B8B",
            "#707070",
            "#545454",
            "#333333",
            "#1A1A1A",
            "#000000",
            "#FF9999",
            "#FFCC99",
            "#FFFF99",
            "#CCFF99",
            "#99FF99",

            "#99FFFF",
            "#99CCFF",
            "#9999FF",
            "#CC99FF",
            "#FF99FF",
            "#FF0000",
            "#FF8000",
            "#FFFF00",
            "#80FF00",
            "#00FF00",
            "#00FFFF",
            "#0080FF",
            "#0000FF",
            "#8000FF",
            "#FF00FF",
            "#800000",
            "#804000",
            "#808000",
            "#408000",
            "#008080",
            "#004080",
            "#004080",
            "#000080",
            "#400080",
            "#800080"
    };

    public static final String[] COLOR_NAME = {
            "THULIAN PINK",
            "ECRU YELLOW",
            "FLORAL VIOLET",
            "FLAMINGO PINK",
            "RED",
            "ROSE RED",
            "HOT PINK",
            "LIGHT SANDLEWOOD BROWN",
            "DARK PURPLE",
            "MAGENTA RED",
            "FIRE ORANGE",
            "GRAPE VIOLET",
            "BURGUNDY RED",
            "LOLLIPOP VIOLET",
            "IRIS VIOLET",
            "AQUA GREEN",
            "SKY BLUE",
            "WHITE",
            "ACID BLUE",
            "ULTRAMARINE BLUE",
            "GRAY",
            "SEA GREEN",
            "HELIOTROPE VIOLET",
            "CHARCOAL GRAY",
            "SACRAMENTO GREEN",
            "INDIGO BLUE",
            "ARMY GREEN",
            "OMESHICHA GREEN",
            "BLACK",
            "YELLOW",
            "SANGRIA RED",
            "FUCHSIA PINK",
            "DARK TEAL BLUE",

            "VIVID BLUE",
            "ELEGANT GRAY",
            "LAGUNA YELLOW",
            "RED",
            "OLIVE GREEN",
            "LEMONADE PINK",
            "PIGEON BLUE",
            "FOSSIL GRAY",
            "MAROON RED",
            "WHITE",
            "CREAM WHITE",
            "TORTILLA BROWN",
            "ABALONE GRAY",
            "BURNT ORANGE",
            "EGGPLANT BLACK",
            "BLACK",
            "MINK GRAY",
            "SOFT MULBERRY RED",
            "WHITE IN GRAY",
            "CARAMEL BROWN",
            "ACTIVE BLACK",
            "ARTOCHOKE GREEN",
            "ELEGANT GRAY",
            "FLAMINGO PINK",
            "LIGHT WHITE IN GRAY",
            "THUNDER GRAY",
            "LAUREL GREEN",
            "CLEAR WHITE",
            "INDIAN SUMMER ORANGE",
            "PINK MIMOSA",
            "DEEPEST WOODLAND GREEN",
            "BANANA YELLOW",
            "INDIGO BLUE",
            "ORANGE",

            "SNOW WHITE",
            "WHITE",
            "STEEL BLUE",
            "BUMBLEBEE YELLOW",
            "BLACK",
            "U.S.FLAG RED",
            "BURGUNDY RED",
            "FLAMINGO PINK",
            "NAVY BLUE",
            "APRICOT ORANGE",
            "LIME GREEN",
            "TROMBONE YELLOW",
            "AZALEA PINK",
            "YELLOW",
            "BLACK GREEN",
            "SPACE BLUE",
            "BABY BLUE",
            "ORANGE NEON",
            "SHADOW GRAY",
            "GRAPE VIOLET",
            "LIME GREEN NEON",
            "RHINO GRAY",
            "AZALEA PINK",
            "GREEN",
            "MUSTARD SEED",
            "LEMON YELLOW NEON",
            "FERRARI RED",
            "GRAY",
            "CARROT ORANGE NEON",
            "BUBBLE GUM NEON",
            "CHARCOAL GRAY",
            "LEMONADE PINK",
            "DEEP SAPPHIRE BLUE",
            "BERMUDA BAY BLUE",

            "MEADOW FLOWER YELLOW",
            "SKY BLUE",
            "SECRET LAVENDER VIOLET",
            "EVENING SHADOW GRAY",
            "BRIGHT RASPBERRY VIOLET",
            "ARMY GREEN",
            "HOT PINK NEON",
            "RED",
            "ONYX BLACK",
            "WHITE ON WHITE",
            "CRYSTAL CLEAR WHITE",
            "UNIVERSAL GRAY",
            "DARK SILK GRAY",
            "ENCHANTED FOREST GREEN",
            "CINNAMON BROWN",
            "BLUE",
            "MAROON RED",
            "INDIGO BLUE",
            "PECAN BROWN",
            "CHOCOLATE BROWN",
            "VERMILLION PINK",
            "IRON GRAY",
            "CREAM WHITE",
            "BLACK GREEN",
            "CIDER ORANGE",
            "MAHOGANY RED",
            "GREEN",
            "ANCHOR",
            "ADZUKI BEAN BROWN",
            "BARN RED",
            "CORN YELLOW",
            "LAVENDER PINK",
            "PEANUT BROWN",
            "SAGE GREEN",

            "FUCHSIA PINK",
            "NATURAL WHITE",
            "RED",
            "BLACK",
            "CLEAR WHITE",
            "SNOW WHITE",
            "WHITE",
            "NUDE",
            "FOREST GREEN",
            "GRAPE VIOLET",
            "AZALEA PINK",
            "MUSTARD YELLOW",
            "LEMONADE PINK",
            "NAVY BLUE",
            "HICKORY BROWN",
            "RUBY PINK",
            "PINEAPPLE YELLOW",
            "MAYA BLUE",
            "CORN YELLOW",
            "MAHOGANY RED",
            "SAILING SHIP TEAL BLUE",
            "BURGUNDY RED",
            "GOLDENROD ORANGE",
            "SANGRIA RED",
            "THISTLE VIOLET",
            "AMARANTH PINK",
            "WHITE IN GRAY",
            "IRON GRAY",
            "LAVA GRAY",
            "BANANA YELLOW",
            "ARMY GREEN",
            "APRICOT ORANGE",
            "BRONZE ORANGE",
            "AQUA GREEN",

            "SPACE BLUE",
            "BLACK",
            "ECRU YELLOW",
            "BURGUNDY RED",
            "EGGPLANT VIOLET",
            "FUCHSIA PINK",
            "NAVY BLUE",
            "MOSS GREEN",
            "STONE GRAY",
            "WHITE",
            "MIDSHIP BLUE",
            "LEMONADE PINK",
            "INDIGO BLUE",
            "LAVENDER PINK",
            "GRAPE VIOLET",
            "SMOKE GRAY",
            "PINEAPPLE YELLOW",
            "TURKISH BLUE",
            "CHOCOLATE BROWN",
            "AFRICAN VIOLET",
            "LIME GREEN",
            "BUMBLEBEE YELLOW",
            "SILVER GRAY",
            "RED",
            "JUNGLE GREEN",
            "GREEN",
            "PECAN BROWN",
            "FADED ROSE PINK",
            "BANANA YELLOW",
            "APRICOT ORANGE",
            "BUBBLE GUM PINK NEON",
            "LEMON YELLOW NEON",
            "PUNCH PINK NEON",
            "APRICOT ORANGE NEON",

            "YELLOW",
            "KISSABLE PINK",
            "MINT GREEN",
            "BABY BLUE",
            "SUBLIME GREEN",
            "MALLARD TREK BLUE",
            "ORCHID VIOLET",
            "U.S. FLAG RED",
            "BLACK",
            "CLEAR WHITE",
            "WHITE",
            "TUSCANY YELLOW",
            "BRONZE ORANGE",
            "SKY BLUE",
            "DEEP PURPLE BLUE",
            "FOREST GREEN",
            "ACID BLUE",
            "CREAMY PINK",
            "CREAM YELLOW",
            "KELLY GREEN",
            "CAROLINA BLUE",
            "BYZANTINE RED",
            "HAWAIIAN TEAL BLUE",
            "ORCHID VIOLET",
            "YELLOW",
            "EGYPTIAN BLUE",
            "ORANGE",
            "CARMINE RED",
            "BLACK GREEN",
            "BANANA YELLOW",
            "FUCHSIA PINK",
            "TANGERINE ORANGE",
            "PINE GREEN",
            "CARAMEL BROWN",

            "ROSEMARY GREEN",
            "CHARCOAL GRAY",
            "ECRU YELLOW",
            "GRAY IN WHITE",
            "WHITE IN GRAY",
            "SNOW WHITE",
            "LEMONADE PINK",
            "SANGRIA RED",
            "SMOKE GRAY",
            "TORTILLA BROWN",
            "TAUPE GRAY",
            "WISTERIA VIOLET",
            "RED",
            "WHITE",
            "PEARL RIVER GARY",
            "RHINO GRAY",
            "STONE GRAY",
            "LAVA GRAY",
            "STEEL GRAY",
            "ASH GRAY",
            "SHADOW GRAY",
            "CHARCOAL GRAY",
            "BLACK",
            "LAVENDER VIOLET",
            "PEACH YELLOW",
            "BANANA YELLOW",
            "MOSS GREEN",
            "SAGE GREEN",
            "SKY BLUE",
            "BABY BLUE",
            "GRAPE VIOLET",
            "ORCHID VIOLET",
            "LILAC VIOLET",
            "RED",

            "HONEY ORANGE",
            "YELLOW",
            "ENGLISH APPLE",
            "KELLY GREEN",
            "BY THE SEA BLUE",
            "AIR FORCE BLUE",
            "BLUE",
            "ELECTRIC VIOLET",
            "LOLLIPOP VIOLET",
            "U.S.FLAG",
            "APRICOT ORANGE",
            "CORN YELLOW",
            "GREEN",
            "FOREST GREEN",
            "TURKISH BLUE",
            "STEEL BLUE",
            "SPACE BLUE",
            "ROYAL VIOLET",
            "VIOLET",
            "ABALONE GRAY",
            "THUNDER GRAY",
            "HARBOR GRAY",
            "FOSSIL GRAY",
            "ASH GRAY",
            "MINK GRAY",
            "STONE GRAY",
            "SHADOW GRAY",
            "CHARCOAL GRAY",
            "BLACK",
            "TAFFY PINK",
            "ECRU YELLOW",
            "BANANA YELLOW",
            "MOSS GREEN",
            "SAGE GREEN",

            "NILE BLUE",
            "PIGEON BLUE",
            "ORCHID VIOLET",
            "ELECTRIC VIOLET",
            "PLUM VIOLET",
            "RED",
            "APRICOT ORANGE",
            "GOLDEN ORANGE",
            "LIME GREEN",
            "GREEN",
            "SKY BLUE",
            "CAROLINA BLUE",
            "EGYPTIAN BLUE",
            "GRAPE VIOLET",
            "FUCHSIA PINK",
            "U.S FLAG RED",
            "CARROT ORANGE",
            "CORN YELLOW",
            "KELLY GREEN",
            "FOREST GREEN",
            "TURKISH BLUE",
            "CARIBBEAN SEA",
            "BLUE",
            "MAUVE VIOLET",
            "VIOLET"
    };
}
